name: Accessibility_Tracker_CLI


# Stages Planned
# Install
# Test
# Report

stages: 
  - install
  - test
  - report

jobs:
  run_test:

    image: node:lts
    
    on: [push]
    
    script: npm i



